// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		int times = Integer.parseInt(args[0]);
		int biggerThan=0;
		int smallerThan=0;
		for (int i=0; i<times; i++)
		{
			int ran = (int)(Math.random()*100);
			if(ran<50)
				smallerThan++;
				else biggerThan++;

		}


		System.out.println("> 0.5: " + biggerThan + " times");
		System.out.println("> 0.5: " + smallerThan + " times");
	}
}
